version: "4"

services:
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cartola
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - "./sql/migrations/20221127164400_init.up.sql:/docker-entrypoint-initdb.d/1.sql"
      - "./sql/migrations/20221202144112_data.down.sql:/docker-entrypoint-initdb.d/2.sql"
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
