name: Django CI

on:
  push:
    branches: [ "main" ]
    paths:
      - "django-panel/**"

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./django-panel
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.10.2
      uses: actions/setup-python@v3
      with:
        python-version: 3.10.2
        
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run Tests
      run: |
        python manage.py test
